#!/bin/bash
# Patches the Info.plist generated by cargo-bundle to add CFBundleDocumentTypes
# so macOS knows PicoNote can open markdown and plain text files via "Open with..."

set -euo pipefail

PLIST="target/release/bundle/osx/PicoNote.app/Contents/Info.plist"

if [ ! -f "$PLIST" ]; then
    echo "Error: $PLIST not found. Run 'cargo bundle --release' first."
    exit 1
fi

PB=/usr/libexec/PlistBuddy

# Add CFBundleDocumentTypes array
$PB -c "Add :CFBundleDocumentTypes array" "$PLIST"

# Markdown documents
$PB -c "Add :CFBundleDocumentTypes:0 dict" "$PLIST"
$PB -c "Add :CFBundleDocumentTypes:0:CFBundleTypeName string 'Markdown Document'" "$PLIST"
$PB -c "Add :CFBundleDocumentTypes:0:CFBundleTypeRole string 'Editor'" "$PLIST"
$PB -c "Add :CFBundleDocumentTypes:0:LSItemContentTypes array" "$PLIST"
$PB -c "Add :CFBundleDocumentTypes:0:LSItemContentTypes:0 string 'net.daringfireball.markdown'" "$PLIST"
$PB -c "Add :CFBundleDocumentTypes:0:CFBundleTypeExtensions array" "$PLIST"
$PB -c "Add :CFBundleDocumentTypes:0:CFBundleTypeExtensions:0 string 'md'" "$PLIST"
$PB -c "Add :CFBundleDocumentTypes:0:CFBundleTypeExtensions:1 string 'markdown'" "$PLIST"

# Plain text documents
$PB -c "Add :CFBundleDocumentTypes:1 dict" "$PLIST"
$PB -c "Add :CFBundleDocumentTypes:1:CFBundleTypeName string 'Plain Text Document'" "$PLIST"
$PB -c "Add :CFBundleDocumentTypes:1:CFBundleTypeRole string 'Editor'" "$PLIST"
$PB -c "Add :CFBundleDocumentTypes:1:LSItemContentTypes array" "$PLIST"
$PB -c "Add :CFBundleDocumentTypes:1:LSItemContentTypes:0 string 'public.plain-text'" "$PLIST"
$PB -c "Add :CFBundleDocumentTypes:1:CFBundleTypeExtensions array" "$PLIST"
$PB -c "Add :CFBundleDocumentTypes:1:CFBundleTypeExtensions:0 string 'txt'" "$PLIST"
$PB -c "Add :CFBundleDocumentTypes:1:CFBundleTypeExtensions:1 string 'text'" "$PLIST"

echo "Patched $PLIST with CFBundleDocumentTypes"
